// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ibreca_data_access.Contexts.IbrecaDB;

namespace ibreca_data_access.Migrations
{
    [DbContext(typeof(IbrecaDBContext))]
    [Migration("20211206013614_Usuarios")]
    partial class Usuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ibreca_data_access.Contexts.IbrecaDB.Models.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(20)")
                        .HasAnnotation("JsonIgnore", "JsonIgnoreCondition.Always");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(8)")
                        .HasAnnotation("JsonIgnore", "JsonIgnoreCondition.Always");

                    b.HasKey("Email")
                        .HasName("pk_usuarios");

                    b.HasIndex("Name")
                        .HasDatabaseName("ind_usuarios_name");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
